# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5d05d56ea0392fbe3a0e7ffcef6b5faabcef9777857e0ce038e43dbe66b5ab6f8670ffcc76822684d4a22458eacb905e3ddfff507999df74cc93cb006d4ed46

test:
  secret_key_base: e4736e8a18f954a704a3938641f7b35a6e9b7bde6ede68bd38daf97dfcc870187a16af9f56632db523389ef871b52097a67d04dfb2475116daee16cec7dcc230

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
